// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX8dKKAthssMMDSW0vvUaG3gWhN9YMLcA',
    appId: '1:474788777029:web:0d7e8bb4e00de98fd4e72c',
    messagingSenderId: '474788777029',
    projectId: 'flutter-chat-2-29c88',
    authDomain: 'flutter-chat-2-29c88.firebaseapp.com',
    storageBucket: 'flutter-chat-2-29c88.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKDGdZDAM46FrW5L5AhIg9JiUaLJIBb18',
    appId: '1:474788777029:android:5ed12f20aaab9b83d4e72c',
    messagingSenderId: '474788777029',
    projectId: 'flutter-chat-2-29c88',
    storageBucket: 'flutter-chat-2-29c88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:474788777029:ios:1bff66ff1d955024d4e72c',
    messagingSenderId: '474788777029',
    projectId: 'flutter-chat-2-29c88',
    storageBucket: 'flutter-chat-2-29c88.firebasestorage.app',
    iosBundleId: 'com.example.flutterChat2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRtKgvT0dIH7IHMLRXka6_bp819Ly4w5I',
    appId: '1:474788777029:ios:1bff66ff1d955024d4e72c',
    messagingSenderId: '474788777029',
    projectId: 'flutter-chat-2-29c88',
    storageBucket: 'flutter-chat-2-29c88.firebasestorage.app',
    iosBundleId: 'com.example.flutterChat2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX8dKKAthssMMDSW0vvUaG3gWhN9YMLcA',
    appId: '1:474788777029:web:fec20bca4213675dd4e72c',
    messagingSenderId: '474788777029',
    projectId: 'flutter-chat-2-29c88',
    authDomain: 'flutter-chat-2-29c88.firebaseapp.com',
    storageBucket: 'flutter-chat-2-29c88.firebasestorage.app',
  );

}